#etape 1: build

FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirement /app/

RUN pip install --no-cache-dir -r requirement.txt --break-system-package

COPY . .

#etape 2: run production

FROM python:3.11-slim

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 8000

ENTRYPOINT [ "PYTHON3", "manage.py" ]

CMD ["runserver","0.0.0.0:8000"]